name: mailer2
version: 0.8.12+1
description: >
  A temporary fork of Kai Sellgren's Mailer (https://github.com/kaisellgren/mailer)
  for aggressive support of replyTo and sender
author: Kai Sellgren <kaisellgren@gmail.com>
homepage: http://github.com/kaisellgren/mailer
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  unittest: '>=0.9.0 <2.0.0'
  mime: '>=0.9.0 <2.0.0'
  logging: '>=0.9.0 <2.0.0'
  crypto: '>=0.9.0 <2.0.0'
  path: '>=0.9.0 <2.0.0'
  intl: '>=0.9.0 <2.0.0'